"""add missing fields to event venue and neighborhood

Revision ID: ac8ed17a845e
Revises: 08d6ba4c0473
Create Date: 2026-02-15 21:45:31.568528
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8ed17a845e'
down_revision: Union[str, None] = '08d6ba4c0473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('time_start', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('time_end', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('url', sa.String(length=500), nullable=True))
    op.add_column('neighborhoods', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))
    op.alter_column('neighborhoods', 'name', server_default=None)
    op.add_column('neighborhoods', sa.Column('fill_color', sa.String(length=50), nullable=True))
    op.add_column('neighborhoods', sa.Column('stroke_color', sa.String(length=50), nullable=True))
    op.add_column('neighborhoods', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('neighborhoods', sa.Column('schedule_open', sa.String(length=10), nullable=True))
    op.add_column('neighborhoods', sa.Column('schedule_close', sa.String(length=10), nullable=True))
    op.add_column('neighborhoods', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('neighborhoods', sa.Column('photos', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('neighborhoods', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('venues', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('venues', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('menu_pdf_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'menu_pdf_url')
    op.drop_column('venues', 'website_url')
    op.drop_column('venues', 'profile_image_url')
    op.drop_column('venues', 'cover_image_url')
    op.drop_column('venues', 'city')
    op.drop_column('neighborhoods', 'recommendations')
    op.drop_column('neighborhoods', 'photos')
    op.drop_column('neighborhoods', 'keywords')
    op.drop_column('neighborhoods', 'schedule_close')
    op.drop_column('neighborhoods', 'schedule_open')
    op.drop_column('neighborhoods', 'short_description')
    op.drop_column('neighborhoods', 'stroke_color')
    op.drop_column('neighborhoods', 'fill_color')
    op.drop_column('neighborhoods', 'name')
    op.drop_column('events', 'url')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'time_end')
    op.drop_column('events', 'time_start')
    # ### end Alembic commands ###
