"""add_user_follows_saves_interests

Revision ID: c900dc224556
Revises: 7bfb9979eb26
Create Date: 2026-02-28 14:11:57.790529
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c900dc224556'
down_revision: Union[str, None] = '7bfb9979eb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'subtype', name='uq_user_interest')
    )
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_index(op.f('ix_user_interests_user_id'), 'user_interests', ['user_id'], unique=False)
    op.create_table('user_venue_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='uq_user_venue_follow')
    )
    op.create_index(op.f('ix_user_venue_follows_id'), 'user_venue_follows', ['id'], unique=False)
    op.create_index(op.f('ix_user_venue_follows_user_id'), 'user_venue_follows', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_venue_follows_venue_id'), 'user_venue_follows', ['venue_id'], unique=False)
    op.create_table('user_saved_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_saved_event')
    )
    op.create_index(op.f('ix_user_saved_events_event_id'), 'user_saved_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_saved_events_id'), 'user_saved_events', ['id'], unique=False)
    op.create_index(op.f('ix_user_saved_events_user_id'), 'user_saved_events', ['user_id'], unique=False)
    op.alter_column('events', 'keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.alter_column('neighborhoods', 'keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('neighborhoods', 'photos',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.create_index(op.f('ix_neighborhoods_id'), 'neighborhoods', ['id'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index(op.f('ix_venues_neighborhood_id'), 'venues', ['neighborhood_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_neighborhood_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_neighborhoods_id'), table_name='neighborhoods')
    op.alter_column('neighborhoods', 'photos',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('neighborhoods', 'keywords',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'keywords',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_saved_events_user_id'), table_name='user_saved_events')
    op.drop_index(op.f('ix_user_saved_events_id'), table_name='user_saved_events')
    op.drop_index(op.f('ix_user_saved_events_event_id'), table_name='user_saved_events')
    op.drop_table('user_saved_events')
    op.drop_index(op.f('ix_user_venue_follows_venue_id'), table_name='user_venue_follows')
    op.drop_index(op.f('ix_user_venue_follows_user_id'), table_name='user_venue_follows')
    op.drop_index(op.f('ix_user_venue_follows_id'), table_name='user_venue_follows')
    op.drop_table('user_venue_follows')
    op.drop_index(op.f('ix_user_interests_user_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_table('user_interests')
    # ### end Alembic commands ###
