"""add date_end to events

Revision ID: de165a4f12a5
Revises: b3c4d5e6f7a8
Create Date: 2026-05-11 15:59:46.128448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de165a4f12a5'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_end', sa.String(length=50), nullable=True))
    op.drop_index('uq_user_interest', table_name='user_interests', postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_interest', 'user_interests', ['user_id', 'category', 'subtype', 'exploration_mode'], unique=True, postgresql_nulls_not_distinct=True)
    op.drop_column('events', 'date_end')
    # ### end Alembic commands ###
